import { existsSync, readFileSync, writeFileSync, mkdirSync, renameSync, mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomBytes } from 'node:crypto';
import { parse, stringify } from 'smol-toml';

export const LOCAL_DATABASE_ID = '00000000-0000-0000-0000-000000000000';
const uuid = /^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i;
// Keep unknown Wrangler options when reconfiguring an existing installation.
export type WranglerConfig = Record<string, any>;
export type Ask = (label: string, fallback: string, validate?: (value: string) => void) => Promise<string>;
export interface RunOptions { input?: string; interactive?: boolean; env?: Record<string,string> }
export type Run = (args: string[], options?: RunOptions) => string;
export interface SetupOptions {
  name?: string; 'base-url'?: string; 'database-name'?: string; 'database-id'?: string;
  'account-id'?: string; reconfigure?: boolean; advanced?: boolean;
  'configure-only'?: boolean; set?: string[];
}
const settings: Record<string, {label:string; validate:(v:string)=>void}> = {
  SITE_NAME: {label:'Site name', validate:nonempty},
  SITE_DESCRIPTION: {label:'Site description', validate:()=>{}},
  SKIN: {label:'Skin (blackboard / chan / corp / dark / harvest)',validate:v=>{if (!['blackboard','chan','corp','dark','harvest'].includes(v)) throw new Error('Choose one of the listed skins.');}},
  LEXICON_COLLECTION: {label:'Document collection',validate:v=>{if (!/^[a-zA-Z][a-zA-Z0-9-]*(?:\.[a-zA-Z][a-zA-Z0-9-]*){2,}$/.test(v)) throw new Error('Use a reverse-domain collection name.');}},
  NOSTR_RELAYS: {label:'Nostr relays (comma-separated)',validate:v=>urlList(v,['wss:','ws:'])},
  NOSTR_CHALLENGE_TTL_MS: {label:'Login challenge lifetime in milliseconds',validate:positiveInteger},
  ARWEAVE_GATEWAY: {label:'Arweave gateway URL',validate:v=>urlList(v,['https:','http:'],true)},
  OTS_CALENDARS: {label:'Timestamp calendars (comma-separated)',validate:v=>urlList(v,['https:','http:'])},
  FORCE_ALLOW_TAGLESS: {label:'Allow untagged records (1 / 0)',validate:flag},
  DISABLE_ZAPS: {label:'Hide Lightning tipping (1 / 0)',validate:flag},
  ENABLE_PINATA: {label:'Enable Pinata uploads (1 / 0; requires PINATA_JWT secret)',validate:flag},
  PIN_MAX_FILE_BYTES: {label:'Maximum upload size in bytes',validate:positiveInteger},
};
function nonempty(value:string) { if (!value.trim()) throw new Error('A value is required.'); }
function flag(value:string) { if (!['0','1'].includes(value)) throw new Error('Enter 1 or 0.'); }
function positiveInteger(value:string) { if (!/^\d+$/.test(value) || !Number.isSafeInteger(Number(value)) || Number(value)<=0) throw new Error('Enter a positive integer.'); }
function urlList(value:string, protocols:string[], single=false) {
  const parts=value.split(',').map(s=>s.trim());
  if (single && parts.length!==1) throw new Error('Enter a single URL.');
  for (const part of parts) {
    let url:URL; try {url=new URL(part);} catch {throw new Error('Enter valid URLs.');}
    if (!protocols.includes(url.protocol) || url.username || url.password || !url.hostname) throw new Error(`Use ${protocols.join(' / ')} URLs without credentials.`);
  }
}
export function validateOrigin(value:string, remote:boolean) {
  urlList(value,remote?['https:']:['http:','https:'],true);
  const url=new URL(value);
  if (url.pathname!=='/' || url.search || url.hash) throw new Error('Enter only the public origin, without a path, query, or fragment.');
  if (remote && ['localhost','127.0.0.1','[::1]'].includes(url.hostname)) throw new Error('Production needs a public HTTPS origin.');
}
function validRemoteId(value:unknown):value is string {return typeof value==='string' && uuid.test(value) && value!==LOCAL_DATABASE_ID;}
function validateName(value:string) {if (!/^[a-z0-9][a-z0-9-]{0,62}$/.test(value)) throw new Error('Use 1–63 lowercase letters, numbers, or hyphens.');}
function validateAccount(value:string) {if (!/^[a-f0-9]{32}$/i.test(value)) throw new Error('Enter the 32-character Cloudflare account ID.');}
function bindings(config:WranglerConfig, key:string):WranglerConfig[] {
  const value=config[key];
  if (value!==undefined && !Array.isArray(value)) throw new Error(`Invalid ${key} configuration.`);
  return value || [];
}
function replaceBinding(config:WranglerConfig, key:string, binding:string, value?:WranglerConfig) {
  const others=bindings(config,key).filter(row=>row.binding!==binding);
  if (value) others.push(value);
  if (others.length) config[key]=others; else delete config[key];
}
function saveConfig(path:string, config:WranglerConfig, original:string|undefined, cwd:string) {
  const text='# Personal deployment configuration. Generated by npm run setup; not tracked by Git.\n'+stringify(config);
  if (original && !original.startsWith('# Tracked template.') && JSON.stringify(parse(original))===JSON.stringify(config)) return;
  if (original) {
    const dir=join(cwd,'backups'); mkdirSync(dir,{recursive:true});
    writeFileSync(join(dir,`wrangler-${Date.now()}-${randomBytes(3).toString('hex')}.toml`),original,{flag:'wx',mode:0o600});
  }
  const temporary=`${path}.tmp`;
  writeFileSync(temporary,text,{mode:0o600}); renameSync(temporary,path);
}

export async function configureWrangler(args:{target:'local'|'remote';options:SetupOptions;ask?:Ask;run:Run;cwd?:string;log?:(message:string)=>void}):Promise<WranglerConfig> {
  const {target,options,ask,run}=args;
  const cwd=args.cwd || process.cwd(); const log=args.log || console.log;
  const path=join(cwd,'wrangler.toml');
  const original=existsSync(path)?readFileSync(path,'utf8'):undefined;
  const template=parse(readFileSync(join(cwd,'wrangler.toml.example'),'utf8')) as WranglerConfig;
  const config=original ? parse(original) as WranglerConfig : structuredClone(template);
  config.vars={...template.vars,...config.vars};
  if (config.env && target==='remote') throw new Error('Named Wrangler environments need explicit deployment handling; this wizard configures the top-level deployment only. Preserve this file and use Wrangler directly.');
  const oldDb=bindings(config,'d1_databases').find(row=>row.binding==='DB');
  const remote=target==='remote';
  let originValid=true;
  try {validateOrigin(config.vars.BASE_URL,remote);} catch {originValid=false;}
  const edit=!original || original.startsWith('# Tracked template.') || options.reconfigure || (remote && (!originValid || !validRemoteId(oldDb?.database_id)));
  async function field(label:string, fallback:string, validate:(v:string)=>void=()=>{}, supplied?:string, prompt=edit):Promise<string> {
    const value=supplied ?? (ask && prompt ? await ask(label,fallback,validate) : fallback);
    validate(value); return value;
  }
  config.name=await field('Worker name',config.name,validateName,options.name);
  config.vars.BASE_URL=(await field('Public URL (production: your workers.dev URL or custom domain)',originValid?config.vars.BASE_URL:(remote?'':'http://localhost:8787'),v=>validateOrigin(v,remote),options['base-url'])).replace(/\/$/,'');
  for (const key of ['SITE_NAME','SITE_DESCRIPTION','SKIN']) {
    config.vars[key]=await field(settings[key].label,String(config.vars[key]),settings[key].validate);
  }
  const advanced=options.advanced || (ask && edit && await field('Review advanced settings? (y / n)','n',v=>{if(!['y','n'].includes(v)) throw new Error('Enter y or n.');})==='y');
  if (advanced) {
    for (const [key,setting] of Object.entries(settings)) {
      if (['SITE_NAME','SITE_DESCRIPTION','SKIN'].includes(key)) continue;
      config.vars[key]=await field(setting.label,String(config.vars[key]),setting.validate,undefined,true);
    }
    const enabled=await field('Enable workers.dev address? (y / n)',config.workers_dev===false?'n':'y',v=>{if(!['y','n'].includes(v)) throw new Error('Enter y or n.');},undefined,true);
    config.workers_dev=enabled==='y';
    const existingDomain=config.routes?.find((r:any)=>typeof r==='object' && r.custom_domain)?.pattern || '';
    const domain=await field('Custom domain (blank for none; - to remove)',existingDomain,v=>{if (v && v!=='-' && !/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$/i.test(v)) throw new Error('Enter a hostname only.');},undefined,true);
    if (domain || existingDomain) {
      const routes=(config.routes || []).filter((r:any)=>!(typeof r==='object' && r.custom_domain));
      if(domain && domain!=='-') routes.push({pattern:domain,custom_domain:true});
      if(routes.length) config.routes=routes; else delete config.routes;
    }
    const oldR2=bindings(config,'r2_buckets').find(row=>row.binding==='GENTOU_BUCKET');
    const bucket=await field('Existing R2 fallback bucket (blank for none; - to remove)',oldR2?.bucket_name || '',v=>{if(v && v!=='-' && !/^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$/.test(v)) throw new Error('Enter a valid R2 bucket name.');},undefined,true);
    replaceBinding(config,'r2_buckets','GENTOU_BUCKET',bucket && bucket!=='-'?{...oldR2,binding:'GENTOU_BUCKET',bucket_name:bucket}:undefined);
  }
  for (const assignment of options.set || []) {
    const index=assignment.indexOf('='); const key=assignment.slice(0,index); const value=assignment.slice(index+1);
    if (index<1 || !settings[key]) throw new Error(`Unknown public setting: ${key}. Secrets must not go in TOML.`);
    settings[key].validate(value); config.vars[key]=value;
  }
  if (remote && config.workers_dev===false && !config.routes?.length) throw new Error('Enable workers.dev or configure a custom domain/route.');
  let dbName=await field('D1 database name',original && !original.startsWith('# Tracked template.') ? oldDb?.database_name || config.name : config.name,validateName,options['database-name']);
  let dbId=options['database-id'] ?? oldDb?.database_id ?? LOCAL_DATABASE_ID;
  if (remote && oldDb && dbName!==oldDb.database_name && !options['database-id']) dbId=LOCAL_DATABASE_ID;
  if (!uuid.test(dbId)) throw new Error('Invalid D1 database UUID.');
  let accountId=options['account-id'] ?? config.account_id ?? process.env.CLOUDFLARE_ACCOUNT_ID;
  if (accountId) validateAccount(accountId);
  const legacy=bindings(config,'kv_namespaces').find(row=>row.binding==='VON_KV');
  if (legacy && (edit || (remote && !legacy.id))) {
    const keep=await field('Keep legacy VON_KV for migration? (y / n)',legacy.id || !remote?'y':'n',v=>{if(!['y','n'].includes(v)) throw new Error('Enter y or n.');},undefined,true);
    if (keep==='n') replaceBinding(config,'kv_namespaces','VON_KV');
    else if (remote) {
      legacy.id=await field('Legacy KV namespace ID',legacy.id || '',v=>{if(!/^[a-f0-9]{32}$/i.test(v)) throw new Error('Enter the 32-character KV namespace ID.');},undefined,true);
    }
  }
  if (remote && !options['configure-only']) {
    log('Connecting to Cloudflare. Setup may create D1 and a draft Worker for secrets; it does not deploy the application.');
    let identity:{accounts:{id:string;name:string}[]};
    try {identity=JSON.parse(run(['whoami','--json']));}
    catch(err) {
      if (!ask) throw new Error('Cloudflare authentication failed. Run npx wrangler login or provide CLOUDFLARE_API_TOKEN.');
      const login=await ask('Open Cloudflare browser login? (y / n)','y',v=>{if(!['y','n'].includes(v)) throw new Error('Enter y or n.');});
      if(login!=='y') throw err;
      run(['login'],{interactive:true}); identity=JSON.parse(run(['whoami','--json']));
    }
    if (!identity.accounts?.length) throw new Error('No Cloudflare accounts are available. Check token permissions.');
    if (!accountId) {
      if(identity.accounts.length===1) accountId=identity.accounts[0].id;
      else {
        log(identity.accounts.map(a=>`  ${a.name}: ${a.id}`).join('\n'));
        accountId=await field('Cloudflare account ID','',validateAccount,undefined,true);
      }
    }
    if (!identity.accounts.some(a=>a.id===accountId)) throw new Error('Selected account is not available to these credentials.');
    config.account_id=accountId;
    const env={CLOUDFLARE_ACCOUNT_ID:accountId as string};
    // Wrangler prioritizes account_id in its config over the environment.
    // Use an isolated account config until the chosen DB has been verified.
    const accountRun = (command:string[]) => {
      const temporary=mkdtempSync(join(tmpdir(),'khamsin-account-'));
      try {
        const accountConfig=join(temporary,'wrangler.toml');
        writeFileSync(accountConfig,stringify({name:config.name,account_id:accountId}),{mode:0o600});
        return run([...command,'--config',accountConfig],{env});
      } finally {rmSync(temporary,{recursive:true,force:true});}
    };
    let databases=JSON.parse(accountRun(['d1','list','--json'])) as {uuid:string;name:string}[];
    if (validRemoteId(dbId)) {
      const selected=databases.find(db=>db.uuid===dbId);
      if(!selected) throw new Error('Configured D1 ID is not in the selected account. It was not replaced.');
      dbName=selected.name;
    } else {
      let selected=databases.find(db=>db.name===dbName);
      if (!selected) {
        log(`Creating D1 database ${dbName}…`);
        accountRun(['d1','create',dbName,'--update-config=false']);
        databases=JSON.parse(accountRun(['d1','list','--json']));
        selected=databases.find(db=>db.name===dbName);
      }
      if (!selected || !validRemoteId(selected.uuid)) throw new Error('Could not find the created D1 database. Retry setup to reconnect by name.');
      dbId=selected.uuid;
    }
    log(`D1: ${dbName} (${dbId})`);
  } else if (remote && !validRemoteId(dbId)) {
    throw new Error('--configure-only for remote requires --database-id (or an existing production binding).');
  }
  if (accountId) config.account_id=accountId;
  const db:WranglerConfig={...oldDb,binding:'DB',database_name:dbName,database_id:dbId,migrations_dir:oldDb?.migrations_dir || 'migrations'};
  // Wrangler uses preview_database_id for local state. Keep the existing local
  // database when promoting a placeholder binding to a real production ID.
  if (oldDb?.database_id===LOCAL_DATABASE_ID && validRemoteId(dbId) && !db.preview_database_id) db.preview_database_id=LOCAL_DATABASE_ID;
  replaceBinding(config,'d1_databases','DB',db);
  saveConfig(path,config,original,cwd);
  log(original?'✓ Wrangler configuration ready (previous versions are backed up when changed).':'✓ Created private wrangler.toml from the tracked example.');
  return config;
}

export function ensureRemoteSecrets(config:WranglerConfig,run:Run,log:(message:string)=>void=console.log,options:{interactive?:boolean;pinataToken?:string}={}) {
  const env=config.account_id?{CLOUDFLARE_ACCOUNT_ID:String(config.account_id)}:undefined;
  let secrets:{name:string}[];
  try {secrets=JSON.parse(run(['secret','list','--format','json'],{env}));}
  catch(err) {
    if (!/Worker .+ not found|\[code: 10007\]/i.test(String(err))) throw err;
    secrets=[];
  }
  if (!secrets.some(s=>s.name==='COOKIE_SECRET')) {
    // Pass secret on stdin, never through argv, TOML, logs, or exported JSON.
    run(['secret','put','COOKIE_SECRET'],{env,input:randomBytes(32).toString('base64')});
    const registered=JSON.parse(run(['secret','list','--format','json'],{env})) as {name:string}[];
    if (!registered.some(s=>s.name==='COOKIE_SECRET')) throw new Error('COOKIE_SECRET was not registered. Retry setup.');
    log('✓ Generated and registered COOKIE_SECRET securely.');
  } else log('✓ Existing COOKIE_SECRET preserved.');
  if (config.vars.ENABLE_PINATA==='1' && !secrets.some(s=>s.name==='PINATA_JWT')) {
    if (options.pinataToken) run(['secret','put','PINATA_JWT'],{env,input:options.pinataToken});
    else if (options.interactive) {
      log('Pinata uploads are enabled. Wrangler will ask for your token with hidden input.');
      run(['secret','put','PINATA_JWT'],{env,interactive:true});
    } else throw new Error('Pinata is enabled but PINATA_JWT is missing. Provide it via an environment variable, or run setup interactively.');
    const registered=JSON.parse(run(['secret','list','--format','json'],{env})) as {name:string}[];
    if (!registered.some(s=>s.name==='PINATA_JWT')) throw new Error('PINATA_JWT was not registered. Retry setup.');
    log('✓ PINATA_JWT registered securely.');
  }
}
